[versions]
jdk = "21"
minecraft = "1.20.6"
neoforge = "26.1.2"

# Mods
# Baritone (https://github.com/MeteorDevelopment/baritone)
baritone = "26.1-SNAPSHOT"
# Orbit (https://github.com/MeteorDevelopment/orbit)
orbit = "0.2.4"
# Starscript (https://github.com/MeteorDevelopment/starscript)
starscript = "0.2.5"
# DiscordRPC (https://github.com/MeteorDevelopment/java-discord-rpc)
discordipc = "1.1"
# Reflections (https://github.com/ronmamo/reflections)
reflections = "0.10.2"
# Netty (https://github.com/netty/netty)
netty = "4.2.7.Final"
# WaybackAuthLib (https://github.com/florianreuth/WaybackAuthLib)
waybackauthlib = "1.1.0"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

# Mods
baritone = { module = "meteordevelopment:baritone", version.ref = "baritone" }

# Libraries
orbit = { module = "meteordevelopment:orbit", version.ref = "orbit" }
starscript = { module = "org.meteordev:starscript", version.ref = "starscript" }
discord-ipc = { module = "meteordevelopment:discord-ipc", version.ref = "discordipc" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
netty-handler-proxy = { module = "io.netty:netty-handler-proxy", version.ref = "netty" }
netty-codec-socks = { module = "io.netty:netty-codec-socks", version.ref = "netty" }
waybackauthlib = { module = "de.florianreuth:waybackauthlib", version.ref = "waybackauthlib" }
